name: Build and Push Container Images

on: workflow_dispatch

jobs:
  filter:
    runs-on: ubuntu-24.04
    outputs:
      services: ${{ steps.filter.outputs.changes}}
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
      - name: filter
        id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # 3.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: .github/utils/file-filters.yaml

  build-push-container-images:
    runs-on: ubuntu-24.04
    needs: filter
    env:
      ACT: false
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJson(needs.filter.outputs.services) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          fetch-depth: 0
      - name: Install task
        uses: supplypike/setup-bin@8e3f88b4f143d9b5c3497f0fc12d45c83c123787 # v4.0.1
        with:
          uri: "https://github.com/go-task/task/releases/download/v3.46.4/task_linux_amd64.tar.gz"
          name: task
          version: v3.46.4
      - name: Auth to DockerHub
        if: ${{ !env.ACT }}
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
      - name: Compute image tag
        id: image-tag
        run: |
          version = foo
          image_tag=foobar
          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "image_tag=${image_tag}" >> $GITHUB_OUTPUT
      - name: Build and Push image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: ${{ matrix.service }}
          push: ${{ !env.ACT }}
          tag: ${{steps.image-tag.outputs.image_tag}}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: typa=gha,mode=max
