name: Run Tests

on:
  workflow_dispatch:

jobs:
  filter:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup Node.js environment
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        # TODO: use specified version + setup caching

      - name: Install task
        uses: supplypike/setup-bin@1fafb085795af4a3f183502f3a9dffa8f7b83217 # v5.0.0
        with:
          uri: "https://github.com/go-task/task/releases/download/v3.46.4/task_linux_amd64.tar.gz"
          name: task
          version: v3.46.4
      - name: Install node deps
        working-directory: services/node/api-node
        run: |
          task install-ci
      - name: Run tests
        working-directory: services/node/api-node
        run: |
          task test