name: Run Tests

on:
  workflow_dispatch:

jobs:
  test-node:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup Node.js environment
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: services/node/api-node/package.json
          cache: 'npm'
          cache-dependency-path: services/node/api-node/package-lock.json 
        # TODO: use specified version + setup caching
      - name: Install task
        uses: supplypike/setup-bin@8e3f88b4f143d9b5c3497f0fc12d45c83c123787 # v4.0.1
        with:
          uri: "https://github.com/go-task/task/releases/download/v3.46.4/task_linux_amd64.tar.gz"
          name: task
          version: v3.46.4
      - name: Install node deps
        working-directory: services/node/api-node
        run: |
          task install-ci
      - name: Run tests
        working-directory: services/node/api-node
        run: |
          task test
  test-go:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup Go environment
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: services/go/api-golang/go.mod
          cache-dependency-path: services/go/api-golang/go.sum
        # TODO: use specified version + setup caching
      - name: Install task
        uses: supplypike/setup-bin@8e3f88b4f143d9b5c3497f0fc12d45c83c123787 # v4.0.1
        with:
          uri: "https://github.com/go-task/task/releases/download/v3.46.4/task_linux_amd64.tar.gz"
          name: task
          version: v3.46.4
      - name: Install app deps
        working-directory: services/go/api-golang
        run: |
          task install-ci
      - name: Run tests
        working-directory: services/go/api-golang
        run: |
          task test